AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda thumbnail generator for AdventureStay package images.
Parameters:
  CodeS3Bucket:
    Type: String
  CodeS3Key:
    Type: String
  PackagesBucketName:
    Type: String
  PackagesTableName:
    Type: String
    Default: adventurestay_packages
Resources:
  ImageProcessorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: S3Access
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:GetObject
            - s3:PutObject
            Resource:
            - Fn::Sub: arn:aws:s3:::${PackagesBucketName}/packages/*
            - Fn::Sub: arn:aws:s3:::${PackagesBucketName}/thumbnails/*
      - PolicyName: DynamoAccess
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - dynamodb:UpdateItem
            Resource:
              Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${PackagesTableName}
  ImageProcessorFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.9
      Handler: image_processor.handler
      Role:
        Fn::GetAtt:
        - ImageProcessorRole
        - Arn
      Timeout: 60
      MemorySize: 512
      Code:
        S3Bucket:
          Ref: CodeS3Bucket
        S3Key:
          Ref: CodeS3Key
      Environment:
        Variables:
          DDB_PACKAGES_TABLE_NAME:
            Ref: PackagesTableName
          THUMBNAIL_PREFIX: thumbnails/
          THUMBNAIL_WIDTH: '300'
  ImageProcessorPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: ImageProcessorFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:s3:::${PackagesBucketName}
Outputs:
  LambdaFunctionName:
    Value:
      Ref: ImageProcessorFunction
