# Generated by Django 5.1.2 on 2025-11-25 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdventurePackageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_code', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(choices=[('TREKKING', 'Trekking'), ('HILLS_STAYCATION', 'Hills Staycation'), ('JUNGLE_SAFARI', 'Jungle Safari'), ('LODGING', 'Lodging')], max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('base_price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('base_price_per_person', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_guests', models.PositiveIntegerField()),
                ('min_nights', models.PositiveIntegerField(default=1)),
                ('max_nights', models.PositiveIntegerField(default=7)),
                ('includes_meals', models.BooleanField(default=False)),
                ('includes_guide', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdventureBookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('num_guests', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=16)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='experiences.adventurepackagemodel')),
            ],
        ),
    ]
