# Generated by Django 5.1.2 on 2025-11-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventurebookingmodel',
            name='guest_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='adventurebookingmodel',
            name='guest_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
