from decimal import Decimal

from django.db import migrations


def seed_packages(apps, schema_editor):
    Package = apps.get_model("experiences", "AdventurePackageModel")

    packages = [
        # Trekking
        {
            "package_code": "TREK001",
            "category": "TREKKING",
            "name": "Himalayan Ridge Trek",
            "location": "Manali",
            "base_price_per_person": Decimal("85.00"),
            "max_guests": 12,
            "min_nights": 3,
            "max_nights": 7,
            "includes_meals": True,
            "includes_guide": True,
            "image_url": "https://images.example.com/trekking/manali.jpg",
        },
        {
            "package_code": "TREK002",
            "category": "TREKKING",
            "name": "Valley of Flowers Expedition",
            "location": "Uttarakhand",
            "base_price_per_person": Decimal("95.00"),
            "max_guests": 10,
            "min_nights": 2,
            "max_nights": 6,
            "includes_meals": True,
            "includes_guide": True,
            "image_url": "https://images.example.com/trekking/valley.jpg",
        },
        {
            "package_code": "TREK003",
            "category": "TREKKING",
            "name": "Western Ghats Trail",
            "location": "Maharashtra",
            "base_price_per_person": Decimal("70.00"),
            "max_guests": 15,
            "min_nights": 2,
            "max_nights": 5,
            "includes_meals": False,
            "includes_guide": True,
            "image_url": "https://images.example.com/trekking/ghats.jpg",
        },
        {
            "package_code": "TREK004",
            "category": "TREKKING",
            "name": "Sikkim Summit Quest",
            "location": "Sikkim",
            "base_price_per_person": Decimal("110.00"),
            "max_guests": 8,
            "min_nights": 4,
            "max_nights": 9,
            "includes_meals": True,
            "includes_guide": True,
            "image_url": "https://images.example.com/trekking/sikkim.jpg",
        },
        {
            "package_code": "TREK005",
            "category": "TREKKING",
            "name": "Nilgiri Sunset Trek",
            "location": "Tamil Nadu",
            "base_price_per_person": Decimal("65.00"),
            "max_guests": 18,
            "min_nights": 1,
            "max_nights": 3,
            "includes_meals": False,
            "includes_guide": True,
            "image_url": "https://images.example.com/trekking/nilgiri.jpg",
        },
        # Hills Staycation
        {
            "package_code": "HILL001",
            "category": "HILLS_STAYCATION",
            "name": "Tea Estate Retreat",
            "location": "Munnar",
            "base_price_per_night": Decimal("150.00"),
            "max_guests": 4,
            "min_nights": 2,
            "max_nights": 6,
            "includes_meals": True,
            "includes_guide": False,
            "image_url": "https://images.example.com/hills/munnar.jpg",
        },
        {
            "package_code": "HILL002",
            "category": "HILLS_STAYCATION",
            "name": "Cedar Chalet Escape",
            "location": "Shimla",
            "base_price_per_night": Decimal("180.00"),
            "max_guests": 5,
            "min_nights": 2,
            "max_nights": 7,
            "includes_meals": True,
            "includes_guide": False,
            "image_url": "https://images.example.com/hills/shimla.jpg",
        },
        {
            "package_code": "HILL003",
            "category": "HILLS_STAYCATION",
            "name": "Mirik Lakefront Villa",
            "location": "Darjeeling",
            "base_price_per_night": Decimal("165.00"),
            "max_guests": 6,
            "min_nights": 1,
            "max_nights": 5,
            "includes_meals": False,
            "includes_guide": False,
            "image_url": "https://images.example.com/hills/darjeeling.jpg",
        },
        {
            "package_code": "HILL004",
            "category": "HILLS_STAYCATION",
            "name": "Cozy Binsar Cottage",
            "location": "Binsar",
            "base_price_per_night": Decimal("140.00"),
            "max_guests": 4,
            "min_nights": 2,
            "max_nights": 7,
            "includes_meals": True,
            "includes_guide": False,
            "image_url": "https://images.example.com/hills/binsar.jpg",
        },
        {
            "package_code": "HILL005",
            "category": "HILLS_STAYCATION",
            "name": "Kodaikanal Artist Loft",
            "location": "Kodaikanal",
            "base_price_per_night": Decimal("130.00"),
            "max_guests": 3,
            "min_nights": 1,
            "max_nights": 4,
            "includes_meals": False,
            "includes_guide": False,
            "image_url": "https://images.example.com/hills/kodaikanal.jpg",
        },
        # Jungle Safari
        {
            "package_code": "JUNG001",
            "category": "JUNGLE_SAFARI",
            "name": "Kanha Panther Safari",
            "location": "Kanha",
            "base_price_per_person": Decimal("105.00"),
            "max_guests": 8,
            "min_nights": 2,
            "max_nights": 5,
            "includes_meals": True,
            "includes_guide": True,
            "image_url": "https://images.example.com/jungle/kanha.jpg",
        },
        {
            "package_code": "JUNG002",
            "category": "JUNGLE_SAFARI",
            "name": "Kaziranga Rhino Watch",
            "location": "Kaziranga",
            "base_price_per_person": Decimal("115.00"),
            "max_guests": 6,
            "min_nights": 3,
            "max_nights": 6,
            "includes_meals": True,
            "includes_guide": True,
            "image_url": "https://images.example.com/jungle/kaziranga.jpg",
        },
        {
            "package_code": "JUNG003",
            "category": "JUNGLE_SAFARI",
            "name": "Bandipur Night Drive",
            "location": "Bandipur",
            "base_price_per_person": Decimal("90.00"),
            "max_guests": 10,
            "min_nights": 2,
            "max_nights": 4,
            "includes_meals": True,
            "includes_guide": True,
            "image_url": "https://images.example.com/jungle/bandipur.jpg",
        },
        {
            "package_code": "JUNG004",
            "category": "JUNGLE_SAFARI",
            "name": "Gir Lion Expedition",
            "location": "Gir",
            "base_price_per_person": Decimal("125.00"),
            "max_guests": 6,
            "min_nights": 2,
            "max_nights": 5,
            "includes_meals": True,
            "includes_guide": True,
            "image_url": "https://images.example.com/jungle/gir.jpg",
        },
        {
            "package_code": "JUNG005",
            "category": "JUNGLE_SAFARI",
            "name": "Periyar Lake Safari",
            "location": "Periyar",
            "base_price_per_person": Decimal("98.00"),
            "max_guests": 9,
            "min_nights": 2,
            "max_nights": 4,
            "includes_meals": True,
            "includes_guide": True,
            "image_url": "https://images.example.com/jungle/periyar.jpg",
        },
        # Rustic lodging
        {
            "package_code": "LODGE001",
            "category": "LODGING",
            "name": "Desert Camp Haven",
            "location": "Jaisalmer",
            "base_price_per_night": Decimal("120.00"),
            "max_guests": 4,
            "min_nights": 1,
            "max_nights": 4,
            "includes_meals": True,
            "includes_guide": False,
            "image_url": "https://images.example.com/lodging/jaisalmer.jpg",
        },
        {
            "package_code": "LODGE002",
            "category": "LODGING",
            "name": "Backwater Clay Homestay",
            "location": "Alleppey",
            "base_price_per_night": Decimal("110.00"),
            "max_guests": 5,
            "min_nights": 1,
            "max_nights": 5,
            "includes_meals": True,
            "includes_guide": False,
            "image_url": "https://images.example.com/lodging/alleppey.jpg",
        },
        {
            "package_code": "LODGE003",
            "category": "LODGING",
            "name": "Coorg Forest Homestead",
            "location": "Coorg",
            "base_price_per_night": Decimal("140.00"),
            "max_guests": 6,
            "min_nights": 2,
            "max_nights": 6,
            "includes_meals": True,
            "includes_guide": False,
            "image_url": "https://images.example.com/lodging/coorg.jpg",
        },
        {
            "package_code": "LODGE004",
            "category": "LODGING",
            "name": "Kumaon Stone Lodge",
            "location": "Kumaon",
            "base_price_per_night": Decimal("135.00"),
            "max_guests": 4,
            "min_nights": 2,
            "max_nights": 6,
            "includes_meals": False,
            "includes_guide": False,
            "image_url": "https://images.example.com/lodging/kumaon.jpg",
        },
        {
            "package_code": "LODGE005",
            "category": "LODGING",
            "name": "Spiti Mudhouse Stay",
            "location": "Spiti",
            "base_price_per_night": Decimal("150.00"),
            "max_guests": 3,
            "min_nights": 2,
            "max_nights": 5,
            "includes_meals": True,
            "includes_guide": False,
            "image_url": "https://images.example.com/lodging/spiti.jpg",
        },
    ]

    for pkg in packages:
        Package.objects.update_or_create(
            package_code=pkg["package_code"],
            defaults={
                "category": pkg["category"],
                "name": pkg["name"],
                "location": pkg["location"],
                "base_price_per_night": pkg.get("base_price_per_night"),
                "base_price_per_person": pkg.get("base_price_per_person"),
                "max_guests": pkg["max_guests"],
                "min_nights": pkg["min_nights"],
                "max_nights": pkg["max_nights"],
                "includes_meals": pkg["includes_meals"],
                "includes_guide": pkg["includes_guide"],
                "image_url": pkg["image_url"],
                "is_active": True,
            },
        )


def remove_seeded_packages(apps, schema_editor):
    Package = apps.get_model("experiences", "AdventurePackageModel")
    codes = [
        "TREK001",
        "TREK002",
        "TREK003",
        "TREK004",
        "TREK005",
        "HILL001",
        "HILL002",
        "HILL003",
        "HILL004",
        "HILL005",
        "JUNG001",
        "JUNG002",
        "JUNG003",
        "JUNG004",
        "JUNG005",
        "LODGE001",
        "LODGE002",
        "LODGE003",
        "LODGE004",
        "LODGE005",
    ]
    Package.objects.filter(package_code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0002_adventurebookingmodel_guest_email_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_packages, remove_seeded_packages),
    ]
